TOTAL_steps: 10000
SEED: 12345
FAST_TRAINING: true
NO_TB: true
DATA_STAY_GPU_FLAG: false

CANO_POSE_TYPE: dfa_rest
VOXEL_DEFORMER_RES: 64
W_CORRECTION_FLAG: true
W_REST_DIM: 0
W_MEMORY_TYPE: voxel

MAX_SCALE: 1.0
MIN_SCALE: 0.0
MAX_SPH_ORDER: 3
INCREASE_SPH_STEP: [1000, 2000, 3000]

INIT_MODE: on_mesh
OPACITY_INIT_VALUE: 0.99
ONMESH_INIT_SUBDIVIDE_NUM: 1
ONMESH_INIT_SCALE_FACTOR: 1.0
ONMESH_INIT_THICKNESS_FACTOR: 0.5

LR_P: 0.00016
LR_P_FINAL: 0.0000016
LR_Q: 0.005
LR_S: 0.005
LR_O: 0.05
LR_SPH: 0.005
W_START_STEP: 2000
LR_W: 0.0001
LR_W_FINAL: 0.00001
LR_W_REST: 0.0
LR_W_REST_FINAL: 0.0

POSE_OPTIM_MODE: adam
POSE_R_BASE_LR: 0.0
POSE_R_BASE_LR_FINAL: 0.0
POSE_R_REST_LR: 0.0
POSE_R_REST_LR_FINAL: 0.0
POSE_T_LR: 0.0
POSE_T_LR_FINAL: 0.0
POSE_OPTIMIZE_START_STEP: 10001

LAMBDA_MASK: 0.0
MASK_LOSS_PAUSE_AFTER_RESET: 100
N_POSES_PER_STEP: 1
RAND_BG_FLAG: true
DEFAULT_BG: [1.0, 1.0, 1.0]
VIEW_BALANCE_FLAG: false
BOX_CROP_PAD: -1

MAX_GRAD: 0.0005
PERCENT_DENSE: 0.01
DENSIFY_START: 100
DENSIFY_INTERVAL: 300
DENSIFY_END: 8000
PRUNE_START: 200
PRUNE_INTERVAL: 300
OPACIT_PRUNE_TH: 0.05
RESET_OPACITY_STEPS: [1002, 2002, 3002, 4002, 5002, 6002, 7002, 8002, 9002]
OPACIT_RESET_VALUE: 0.05
REGAUSSIAN_STD: 0.02
REGAUSSIAN_STEPS: []

CANONICAL_SPACE_REG_K: 3
LAMBDA_STD_Q: 0.001
LAMBDA_STD_S: 0.001
LAMBDA_STD_O: 0.001
LAMBDA_STD_CD: 0.001
LAMBDA_STD_CH: 0.001
LAMBDA_STD_W: 0.5
LAMBDA_SMALL_SCALE: 0.05
LAMBDA_W_NORM: 0.1
LAMBDA_LPIPS: 0.0
LAMBDA_SSIM: 0.1
